services:
  tenant_centro_medico_mysql:
    image: mysql:8.0
    container_name: tenant_centro_medico_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tenant_centro_medico_db
    ports:
      - "3307:3306"
    volumes:
      - tenant_centro_medico_mysql_data:/var/lib/mysql
    networks:
      - tenant_centro_medico_net

  tenant_centro_medico_mongo:
    image: mongo:6.0
    container_name: tenant_centro_medico_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - tenant_centro_medico_mongo_data:/data/db
    networks:
      - tenant_centro_medico_net

  tenant_centro_medico_api:
    build: .
    container_name: tenant_centro_medico_api
    ports:
      - "3000:3000"
    depends_on:
      - tenant_centro_medico_mongo
      - tenant_centro_medico_mysql 
      - tenant_centro_medico_redis
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "if [ \"$NODE_ENV\" = \"development\" ]; then npm run dev; else npm start; fi"
    env_file:
      - .env
    networks:
      - tenant_centro_medico_net
      - tenant_centro_medico_proxy

  tenant_centro_medico_redis:
    container_name: tenant_centro_medico_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tenant_centro_medico_net

networks:
  tenant_centro_medico_net:
  tenant_centro_medico_proxy:
    external: true

volumes:
  tenant_centro_medico_mongo_data:
  tenant_centro_medico_mysql_data:
